#!/usr/bin/env bash
# Creates three nodes. A network map and notary node and two regular nodes that can be extended with cordapps.

set -euo pipefail
trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT
export CAPSULE_CACHE_DIR=cache

function runNode {
    pushd $1
    ( java -jar JAR_NAME )&
    popd
}

for dir in `ls`; do
    if [ -d $dir ]; then
        runNode $dir
    fi
done

read -p 'Any key to exit'
kill $(jobs -p)
